name: BlackSmithImagery
favicon: null
layout_spectrum: 0.636711286380887
typography_spectrum: 0.5012229948770255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9834403360728174
  lightness: 0.3370508274529129
  saturation: 0.9354644953273237
  rhythmicContrast: 0.6690680030733347
purpose: []
